spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cat_shop
    username: gorjan
    password: gorjan
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
